version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  server:
    image: judge0/judge0:1.13.0
    volumes:
      - ./services/judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./services/judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:13.0
    env_file: ./services/judge0/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:6.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: ./services/judge0/judge0.conf
    volumes:
      - redis-data:/data
    <<: *default-logging
    restart: always
  
  frontend:
    build:
      context: frontend/.
      dockerfile: ../services/frontend/Dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_BACKEND=${BACKEND}
    volumes:
      -  ./frontend:/app
    restart: always

  backend:
    build:
      context: backend/.
      dockerfile: ../services/backend/Dockerfile
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      -  ./backend:/app
    restart: always
  
  mainDB:
    image: mongo:latest
    volumes:
      - ./database:/data/db
    restart: always
    ports:
      - 27017:27017

volumes:
  postgres-data:
  redis-data: